# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "rnbase.xcodeproj")
    build_app(workspace: "rnbase.xcworkspace", scheme: "rnbase")
    upload_to_testflight
  end

  desc "Push a new version build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "rnbase.xcodeproj")
    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "rnbase.xcodeproj",
      target_filter: "rnbase", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Release"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )
    build_app(workspace: "rnbase.xcworkspace", scheme: "rnbase")
    upload_to_testflight(changelog: "[DEVELOPMENT_ENV]", skip_waiting_for_build_processing: true)

    # after uploaded to testflight, notify to tester
  end
end
